bases:
- ../base
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  env: dev
  io.kompose.service: dev-mystok-app

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: mystok-deploy
  path: patch1.yaml
